version: '3.9'

services:
  app:
    build:
      context: ./php
      dockerfile: Dockerfile
    container_name: app
    volumes:
      - ./../app:/var/www/app
    environment:
      APP_ENV: dev
      DATABASE_URL: postgres://symfony:symfony@db:5432/symfony
    networks:
      - symfony_network

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    container_name: nginx
    ports:
      - "8080:80"
    volumes:
      - ./../app:/var/www/app
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - symfony_network

  db:
    image: postgres:15
    container_name: postgres
    environment:
      POSTGRES_USER: symfony
      POSTGRES_PASSWORD: symfony
      POSTGRES_DB: symfony
    volumes:
      - ./postgres/data:/var/lib/postgresql/data #Способ через привязанную директорию
#      - postgres_data:/var/lib/postgresql/data  #Способ через через именнованый том
    ports:
      - "5432:5432"
    networks:
      - symfony_network

#именованный том
#volumes:
#  postgres_data:

networks:
  symfony_network: